### ISSUE TITLE
[bug] Ticket cost not working?

### ISSUE THREAD

**Issue by bitbooster** [monich/harbour-matkakortti#6]
I have season ticket for the zones BC (and some value loaded on my HSL card), and yesterday I made a trip to Helsinki (zone A), so I paid a 'zone extension ticket' (price 2.50 EUR).
I noticed that the harbour-matkakortti app reported incorrectly the cost at 0 EUR.
That was both while the ticket was still valid and afterwards when looking at the card history (see screenshot).
I checked also that with the official HSL app on an Android device, and it did report the correct price.

![ticket](https://user-images.githubusercontent.com/553677/75158025-fd168100-571d-11ea-9098-9572cac17077.jpg)

**Comment by monich** [comment]
Could you install [NFC Logger from OpenRepos](https://openrepos.net/content/slava/nfc-logger), run it, then let my app read the ticket, save the tarball in NFC Logger (Pack and Send from the pulley menu, and then either send it from there of choose Save to Documents to save it to the filesystem) and send it to slava(at)monich.com. That way I would know what's coming out of your travel card. I never had to buy a zone extension ticket, so that part was left untested.

Of course I could pay 2.50 EUR for an extension ticket myself but I would rather get a trace for free :)

**Comment by monich** [comment]
Ouch, apparently before I can buy an extension ticket, I would have to buy a season ticket first (which I don't need)... That's significantly more than just 2.50 EUR. I don't think I'm going to do that.

BTW, was the price right in the history tab?

**Comment by monich** [comment]
Commit 5976aff might help, although it's hard to tell without knowing what exactly is on the card. Could you install rpm from here (the first one from the list):

https://build.merproject.org/package/binaries/home:slava:webhooks/harbour-matkakortti?repository=sailfishos_1.1.7.25_latest_armv7hl

and confirm that it works (or doesn't work)?

**Comment by bitbooster** [comment]
That's odd, I downloaded and installed harbour-matkakortti-1.0.7+extension.20200302140043.2.g5976aff-3.1.armv7hl.rpm and tried to use it but... it doesn't read the HSL card. 
I uninstalled that one and re-installed the latest public version in OpenRepos and still doesn't read the card (and yes, NFC is enabled on the phone).
Anyway I'll try again alter and report on the result.

About sending a dump of the card, well, I'm not too keen on giving data on any personal card to anyone else, sorry. However, if the structure of the card is somehow known so it's possible to say that a specific field is at offset XX, I'd be ok to fetch that field from the card dump.

**Comment by monich** [comment]
Could it be that nothing worked because of the problem described [here](https://openrepos.net/comment/31477#comment-31477)? In short, try it again after recharging the phone (or connecting the charger).

**Comment by monich** [comment]
And yes, it's understandable that you don't want to provide full dump to someone you don't know. I would do the same :D

There's something in there which might be considered personal info e.g. ids of the tram/bus and possibly stops where you validated your card. No name (like on Tampere card), address or personal id number, though. There's a document [here](https://github.com/HSLdevcom/hsl-card-java/blob/master/HSL%20Matkakortin%20kuvaus%20ja%20API%20kehitt%C3%A4jille%20v1.11.pdf) and it seems to reflect the reality, in case if you're interested.

**Comment by bitbooster** [comment]
Not sure what was the issue with reading my bus card this morning (but indeed, phone charge was almost 60%, IIRC) but I tried again after recharging and... success! 
The new app version seems to read the extension ticket just fine.
![ticketok](https://user-images.githubusercontent.com/553677/75813574-e06eee80-5d98-11ea-97e1-e1305ee01e4e.jpg)

**Comment by monich** [comment]
yey \o/

**Comment by monich** [comment]
Please check if everything is OK with version 1.0.8 from either OpenRepos (already there) or Jolla Store (may take a few days)

**Comment by bitbooster** [comment]
Confirmed working with 1.0.8 (at least with the last -and only- used extension ticket).
Thanks!

**Comment by monich** [comment]
Great, closing!
